// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQEvAp6XPe1tJYLGb7lkUgcCMmqr_kinI',
    appId: '1:677987214244:web:310a2cf8da8be2b5205731',
    messagingSenderId: '677987214244',
    projectId: 'halihanem-2',
    authDomain: 'halihanem-2.firebaseapp.com',
    storageBucket: 'halihanem-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlcCD6E7b3AeZktiIXAjPPI1a5yCRdaHY',
    appId: '1:677987214244:android:cb97f5532ce56242205731',
    messagingSenderId: '677987214244',
    projectId: 'halihanem-2',
    storageBucket: 'halihanem-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw-en-26YQSruDkgBM-xc038IjaWpdz_Q',
    appId: '1:677987214244:ios:f19e290b786baa8b205731',
    messagingSenderId: '677987214244',
    projectId: 'halihanem-2',
    storageBucket: 'halihanem-2.firebasestorage.app',
    androidClientId: '677987214244-vhoucoup4a804796buern42c24ft6f71.apps.googleusercontent.com',
    iosClientId: '677987214244-p8ctbgo646m9l9t5bth7hqkndb33482t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSoruCozum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw-en-26YQSruDkgBM-xc038IjaWpdz_Q',
    appId: '1:677987214244:ios:f19e290b786baa8b205731',
    messagingSenderId: '677987214244',
    projectId: 'halihanem-2',
    storageBucket: 'halihanem-2.firebasestorage.app',
    androidClientId: '677987214244-vhoucoup4a804796buern42c24ft6f71.apps.googleusercontent.com',
    iosClientId: '677987214244-p8ctbgo646m9l9t5bth7hqkndb33482t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSoruCozum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9mYB5yvLeeS449SVpFKp9mctwqKiDuek',
    appId: '1:677987214244:web:cf8a58244eef3442205731',
    messagingSenderId: '677987214244',
    projectId: 'halihanem-2',
    authDomain: 'halihanem-2.firebaseapp.com',
    storageBucket: 'halihanem-2.firebasestorage.app',
  );

}